/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '11/17/19, 1:14 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-754.6.3.el6.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15' 
 * Generated on web client 'http://localhost:10080/SASStudio/38/main?locale=en_US&zone=GMT-07%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glmselect data=WORK.COLODATA outdesign(addinputvars)=Work.reg_design 
		plots=(criterionpanel);
	model Completers_Pct=Math_02_Unsat_Pct Math_03_Partially_Proficient_Pct 
		Math_04_Proficient_Pct Math_05_Advanced_Pct Reading_02_Unsat_Pct 
		Reading_03_Partially_Proficient_ Reading_04_Proficient_Pct 
		Reading_05_Advanced_Pct Writing_02_Unsat_Pct Writing_03_Partially_Proficient_ 
		Writing_04_Proficient_Pct Writing_05_Advanced_Pct / showpvalues 
		selection=backward
    
   (select=sbc);
run;

proc reg data=Work.reg_design alpha=0.05 plots(only)=(diagnostics residuals 
		observedbypredicted);
	ods select DiagnosticsPanel ResidualPlot ObservedByPredicted;
	model Completers_Pct=&_GLSMOD /;
	run;
quit;

proc delete data=Work.reg_design;
run;